# 此服务没有通过 selector 指定 pod

# 这个文档yaml, 不能用

apiVersion: v1
kind: Service
metadata:
  name: my-service-1   # 内部应用访问这个域名
spec:
#  selector:   # 没有通过 selector 选择 pod
#    app: MyApp
  ports:
    - protocol: TCP
      port: 80        # 内部访问 80 端口
      targetPort: 443 # 映射到外部目标的 9376 端口
  # 注意！这里故意没写 selector，所以 K8s 不会自动创建 EndpointSlice
  
#  这里新出现了一个概念: "EndpointSlice" 他的意思是, 其实我们通过
#  selector 选择pod的时候, 底层会创建一个 EndpointSlice 对象, 是他和 pod进行的通信
  type: NodePort





# 使用 minikube service my-service --url 访问


---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-service-1 # 按惯例将 Service 的名称用作 EndpointSlice 名称的前缀
  labels:
    # 你应设置 "kubernetes.io/service-name" 标签。
    # 设置其值以匹配 Service 的名称
    kubernetes.io/service-name: my-service-1
addressType: IPv4
ports:
  - name: '' # 应与上面定义的 Service 端口的名称匹配
    appProtocol: http
    protocol: TCP
    port: 443
endpoints:  # 此列表中的 IP 地址可以按任何顺序显示
  #多个地址会创建多个pod进行负载均衡
  - addresses:
      - "39.156.70.239"
#  - addresses:
#      - "10.1.2.3"