# 如果 properties 和 yaml 同时配置了相同的配置, properties 文件生效
# 如果 properties  通过 spring.config.import 又引入了其他的配置 如下, 此时引入的配置生效
server.port=9000

spring.banner.location=banner.txt


# 引入其他配置文件
spring.config.import[0]=classpath:log.properties
spring.config.import[1]=classpath:actuator.properties

