
# 关于 spring 日志的配置



# 调整日志级别, root 其实是一个组, 这个组下包含了很多的包
logging.level.root=info

# 单独调整某个包的日志级别
logging.level.com.sj.springboot01demo=info


# =======  日志格式 =========




# =======   日志分组   ======

# 定义了一个 biz 组,  以下2个包都属于 biz 组
logging.group.biz=com.sj.springboot01demo.controller,com.sj.springboot01demo.service

# 在指定biz 组 是debug级别
logging.level.biz=debug


# =======  调整某个包的日志级别 =======
# 调整 mapper 包为 debug 级别
logging.level.com.sj.springboot01demo.mapper=info



##  ==================   日志的文件输出 ======================
# 默认情况下,不会输出文件, 只会在 控制台输出

# 将日志输出, 这个日志输出在了 shijian-demo目录下
# 应该是输出在最外层的项目的文件夹下

#logging.file.name=boot.log


# 这种写法是指定一个 路径, 日志会被写入这个路径
# 日志名字为 spring.log
#logging.file.path=




# ========================  文件归档与主动切割   =====================================

# 日志存档的文件格式
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

# 默认值 false
# 启动时是否清除以前存档
logging.logback.rollingpolicy.clean-history-on-start=false


# 每个日志文件的最大大小 默认 10MB
logging.logback.rollingpolicy.max-file-size=10MB

# 默认值 0B
# 日志文件被删除之前, 可以容纳的最大大小. 设置 1GB 则磁盘超过 1GB日志就会 删除旧的日志
logging.logback.rollingpolicy.total-size-cap=0B

# 日志保存的最大天数, 默认值 7天
logging.logback.rollingpolicy.max-history=7







