
spring.application.name=springmvc-restful-crud


# crud??? ??? spring_tx ???????
spring.datasource.url=jdbc:mysql://localhost:3306/spring_tx
spring.datasource.username=root
spring.datasource.password=shijian110
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver