spring:
  application:
    name: service-mail
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  mail:
    username: xxxx
    password: asssdsadas
    host: ssssssssss




