

spring.datasource.url=jdbc:mysql://localhost:3306/mybatis-example
spring.datasource.username=root
spring.datasource.password=shijian110
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 告诉mybatis  mapper的xml文件在哪里, 默认就是 classpath:mapper/**.xml
mybatis.mapper-locations=classpath:mapper/**.xml
# 开启驼峰命名规则
mybatis.configuration.map-underscore-to-camel-case=true


// 分步查询 有时候不需要立即运行,我们希望在用到的时候再去查询, 可以开启延迟加载功能
mybatis.configuration.lazy-loading-enabled=true
mybatis.configuration.aggressive-lazy-loading=false


logging.level.com.sj.mapper=debug