apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi               # 指定容量大小
  accessModes:                 # 访问模式
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /root/nfs/data
    server: 10.15.0.25

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs   # 通过存储类（StorageClass）名称来筛选 PV
  # selector:             # 通过标签形式
  #   matchLabels:
  #     pv-name: nfs-pvc


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-pvc-demo
  labels:
    app: pv-pvc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-pvc-demo
  # pod的定义
  template:
    metadata:
      name: pv-pvc-demo
      labels:
        app: pv-pvc-demo
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo 'Hello NFS!' >> /data/index.html; sleep 1; done"]
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc