# 安装 k8s 插件 , 通过 kpod  kDeployment  kservice 直接创建 文件模板
apiVersion: v1
kind: Pod
metadata:
  name: title
  labels:
    role: title
spec:
  containers:
    - name: title
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: title
  labels:
    app: title
spec:
  replicas: 1
  selector:
    matchLabels:
      app: title
  template:
    metadata:
      name: title
      labels:
        app: title
    spec:
      containers:
        - name: title
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: title
spec:
  selector:
    app: title
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
