# 基本的pod的写法


# 固定写法
apiVersion: v1
# 定义资源种类
kind: Pod
# 元数据信息
metadata:
  # 资源名称, 就是pod的名称
  name: nginx1
# 规格信息, 对pod预期行为的规约
spec:
  # 容器列表(1个pod可以管理多个容器)
  containers:
    # 容器的名字
    - name: nginx
      # 容器使用的镜像
      image: nginx:1.19
      # 容器暴露的 端口信息
      ports:
        # 容器端口
        - containerPort: 80




# 通过 yaml文件运行pod
# kubectl apply -f pod01-nignx.yaml
# 返回的结果
#  pod/nginx created

# 再次运行pod文件
# kubectl apply -f pod01-nignx.yaml

# 返回结果是 未改变, 说明 kubectl apply -f 命令, 既可以运行,也可以修改
# pod/nginx unchanged


# 获取pod信息
# kubectl get pod

# 查看pod详情
# kubectl describe pod nginx


# 删除pod

# 根据名称删除
# kubectl delete pod nginx

# 根据文件删除
# kubectl delete -f pod01-nignx.yaml
