spring.application.name=service-order
server.port=8000

# 默认值，不写也可以
spring.cloud.nacos.server.adder=127.0.0.1:8848


# 关闭引导检查, 在配置了 nacos配置中心后, 必须要配置 nacos中的配置文件
# 设置成了 false ,此时 就可以不指定nacos中的配置了
spring.cloud.nacos.config.import-check.enabled=false
#spring.config.import=nacos:service-order.properties

spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos




